apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paytm-ingress
  namespace: paytm-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /payment-gateway
        pathType: Prefix
        backend:
          service:
            name: payment-gateway-service
            port:
              number: 9001
      - path: /wallet-service
        pathType: Prefix
        backend:
          service:
            name: wallet-service-service
            port:
              number: 9002
      - path: /transaction-service
        pathType: Prefix
        backend:
          service:
            name: transaction-service-service
            port:
              number: 9003
      - path: /user-service
        pathType: Prefix
        backend:
          service:
            name: user-service-service
            port:
              number: 9004
      - path: /profile-service
        pathType: Prefix
        backend:
          service:
            name: profile-service-service
            port:
              number: 9005
      - path: /kyc-service
        pathType: Prefix
        backend:
          service:
            name: kyc-service-service
            port:
              number: 9006
      - path: /bank-service
        pathType: Prefix
        backend:
          service:
            name: bank-service-service
            port:
              number: 9007
      - path: /loan-service
        pathType: Prefix
        backend:
          service:
            name: loan-service-service
            port:
              number: 9008
      - path: /investment-service
        pathType: Prefix
        backend:
          service:
            name: investment-service-service
            port:
              number: 9009
      - path: /email-service
        pathType: Prefix
        backend:
          service:
            name: email-service-service
            port:
              number: 9010
      - path: /sms-service
        pathType: Prefix
        backend:
          service:
            name: sms-service-service
            port:
              number: 9011
      - path: /push-service
        pathType: Prefix
        backend:
          service:
            name: push-service-service
            port:
              number: 9012