apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: paytm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
      containers:
      - name: wallet-service
        image: pradipshinde/wallet-service:BUILD_NUMBER
        ports:
        - containerPort: 9002
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-service-service
  namespace: paytm-app
spec:
  selector:
    app: wallet-service
  ports:
  - port: 9002
    targetPort: 9002
  type: ClusterIP
